### ISSUE TITLE
Kevin please comment your code

### ISSUE THREAD

**Issue by surrsurus** [team484/blu#1]
Self-Explantatory

**Comment by AcePazuzu** [comment]
No

**Comment by surrsurus** [comment]
I'm offended. I would prefer that all code is commented to the highest degree.

**Comment by AcePazuzu** [comment]
There is a slight problem there. Mewsus Christ has told me that commenting code to the highest degree is blasphemy. It must be to a lesser degree.

**Comment by surrsurus** [comment]
I'm sorry as the Arch Paladin of Pope Commentus II, I must engage in a holy crusade against those who refuse to comment their code.

**Comment by AcePazuzu** [comment]
As the High Warlock of Mewsus Christ, savior of Lord Arceus' holy land, I must uphold the tenants of Mewsianity at all costs. Even if I must destroy Pope Commentus II and all he stands for. Pope Sloking IV is the only pope to be obeyed.

**Comment by surrsurus** [comment]
Wow, go back to 315 BC Nerd its all about Pope Commentus II now.

**Comment by AcePazuzu** [comment]
If that is how you will be, I will resort even to calling upon the Antipaladins of Giratina, my Lord's mortal enemies, to defeat your false religion of Commentium.

**Comment by surrsurus** [comment]
Wow ok bye nerd

**Comment by surrsurus** [comment]
Wow ok bye nerd

**Comment by AcePazuzu** [comment]
Cya skruub
